# Generated by Django 3.2.25 on 2024-08-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfupload',
            name='pdf',
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
